version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      TZ: Asia/Jakarta
    ports:
      - 3308:3306
    networks:
      - arc_network
    volumes:
      - ./app/:/user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 8081:80
    networks:
      - arc_network

networks:
  arc_network:
    external: true